### ISSUE TITLE
Send appeals

### ISSUE THREAD

**Issue by jannikluhn** [brainbot-com/shutter#75]
If accused, send an appeal in order to not get slashed.

**Comment by schmir-at-bb** [comment]
Will other keypers send appeals even if they are not accused?

**Comment by jannikluhn** [comment]
That would be very nice of them, we can do this. Not sure if we have to do staggering in this case though (shouldn't happen normally, but could be a griefing attack vector).

**Comment by jannikluhn** [comment]
done.
